name: Deployment Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deep: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Lint
        run: pylint pom

  Tests:
    needs: [Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install Playwright browsers
        run: playwright install
      - name: Run tests
        working-directory: ./pom
        run: python -m pytest -s -v --html=reports/pwreport3.html --capture=tee-sys --video retain-on-failure
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: pom/reports
          retention-days: 30


